const sampleData = {
  products: [
    {
      id: 1,
      name: "판타지 소설",
      slug: "/fantasy-novel-1",
      category: "Books",
      images: ["/assets/images/p1-1.jpeg", "/assets/images/p1-2.jpeg"],
      price: "30000",
      brand: "우리서점",
      rating: "4.5",
      numReviews: 10,
      stock: 5,
      description: "신비로운 판타지의 세계로",
      isFeatured: true,
      createdAt: new Date(),
    },
    {
      id: 2,
      name: "테니스 교실",
      slug: "/tennis-class-1",
      category: "sports",
      images: ["/assets/images/p2-1.jpeg", "/assets/images/p2-2.jpeg"],
      price: "32000",
      brand: "nike",
      rating: "4.2",
      numReviews: 8,
      stock: 10,
      description: "테니스 교실에서 배우는 테니스의 모든 것",
      isFeatured: true,
      createdAt: new Date(),
    },
    {
      id: 3,
      name: "하하엄마의 하하하",
      slug: "/haha-mom-1",
      category: "Track Pants",
      images: ["/assets/images/p3-1.jpeg", "/assets/images/p3-2.jpeg"],
      price: "10000",
      brand: "우리점",
      rating: "4.9",
      numReviews: 3,
      stock: 0,
      description: "재미있는 책 ",
      isFeatured: true,
      createdAt: new Date(),
    },
    {
      id: 4,
      name: "오늘의 요리",
      slug: "/cooking-today-1",
      category: "Track Pants",
      images: ["/assets/images/p4-1.jpeg", "/assets/images/p4-2.jpeg"],
      price: "4000",
      brand: "the born korea",
      rating: "3.6",
      numReviews: 5,
      stock: 10,
      description: "오늘의 요리는 오늘의 요리를 소개합니다. 맛있는 요리를 만들어보세요",
      isFeatured: true,
      createdAt: new Date(),
    },
    {
      id: 5,
      name: "판타지 소설",
      slug: "/fantasy-novel-2",
      category: "Books",
      images: ["/assets/images/p1-1.jpeg", "/assets/images/p1-2.jpeg"],
      price: "30000",
      brand: "우리서점",
      rating: "4.5",
      numReviews: 10,
      stock: 5,
      description: "신비로운 판타지의 세계로",
      isFeatured: true,
      createdAt: new Date(),
    },
    {
      id: 6,
      name: "테니스 교실",
      slug: "/tennis-class-2",
      category: "sports",
      images: ["/assets/images/p2-1.jpeg", "/assets/images/p2-2.jpeg"],
      price: "32000",
      brand: "nike",
      rating: "4.2",
      numReviews: 8,
      stock: 10,
      description: "테니스 교실에서 배우는 테니스의 모든 것",
      isFeatured: true,
      createdAt: new Date(),
    },
    {
      id: 7,
      name: "하하엄마의 하하하",
      slug: "/haha-mom-2",
      category: "Track Pants",
      images: ["/assets/images/p3-1.jpeg", "/assets/images/p3-2.jpeg"],
      price: "10000",
      brand: "우리점",
      rating: "4.9",
      numReviews: 3,
      stock: 0,
      isFeatured: true,
      description: "재미있는 책 ",
      createdAt: new Date(),
    },
    {
      id: 8,
      name: "오늘의 요리",
      slug: "/cooking-today-2",
      category: "Track Pants",
      images: ["/assets/images/p4-1.jpeg", "/assets/images/p4-2.jpeg"],
      price: "4000",
      brand: "the born korea",
      rating: "3.6",
      numReviews: 5,
      stock: 10,
      isFeatured: true,
      description: "오늘의 요리는 오늘의 요리를 소개합니다. 맛있는 요리를 만들어보세요",
      createdAt: new Date(),
    },
    {
      id: 9,
      name: "판타지 소설",
      slug: "/fantasy-novel-3",
      category: "Books",
      images: ["/assets/images/p1-1.jpeg", "/assets/images/p1-2.jpeg"],
      price: "30000",
      brand: "우리서점",
      rating: "4.5",
      numReviews: 10,
      stock: 5,
      description: "신비로운 판타지의 세계로",
      isFeatured: true,
      createdAt: new Date(),
    },
    {
      id: 10,
      name: "판타지 소설",
      slug: "/fantasy-novel-4",
      category: "Books",
      images: ["/assets/images/p1-1.jpeg", "/assets/images/p1-2.jpeg"],
      price: "30000",
      brand: "우리서점",
      rating: "4.5",
      numReviews: 10,
      stock: 5,
      description: "신비로운 판타지의 세계로",
      isFeatured: true,
      createdAt: new Date(),
    },
    {
      id: 11,
      name: "테니스 교실",
      slug: "/tennis-class-3",
      category: "sports",
      images: ["/assets/images/p2-1.jpeg", "/assets/images/p2-2.jpeg"],
      price: "32000",
      brand: "nike",
      rating: "4.2",
      numReviews: 8,
      stock: 10,
      description: "테니스 교실에서 배우는 테니스의 모든 것",
      isFeatured: true,
      createdAt: new Date(),
    },
    {
      id: 12,
      name: "테니스 교실",
      slug: "/tennis-class-4",
      category: "sports",
      images: ["/assets/images/p2-1.jpeg", "/assets/images/p2-2.jpeg"],
      price: "32000",
      brand: "nike",
      rating: "4.2",
      numReviews: 8,
      stock: 10,
      description: "테니스 교실에서 배우는 테니스의 모든 것",
      isFeatured: true,
      createdAt: new Date(),
    },
    {
      id: 13,
      name: "하하엄마의 하하하",
      slug: "/haha-mom-3",
      category: "Track Pants",
      images: ["/assets/images/p3-1.jpeg", "/assets/images/p3-2.jpeg"],
      price: "10000",
      brand: "우리점",
      rating: "4.9",
      numReviews: 3,
      stock: 0,
      isFeatured: true,
      description: "재미있는 책 ",
      createdAt: new Date(),
    },
    {
      id: 14,
      name: "하하엄마의 하하하",
      slug: "/haha-mom-4",
      category: "Track Pants",
      images: ["/assets/images/p3-1.jpeg", "/assets/images/p3-2.jpeg"],
      price: "10000",
      brand: "우리점",
      rating: "4.9",
      numReviews: 3,
      stock: 0,
      isFeatured: true,
      description: "재미있는 책 ",
      createdAt: new Date(),
    },
    {
      id: 15,
      name: "오늘의 요리",
      slug: "/cooking-today-3",
      category: "Track Pants",
      images: ["/assets/images/p4-1.jpeg", "/assets/images/p4-2.jpeg"],
      price: "4000",
      brand: "the born korea",
      rating: "3.6",
      numReviews: 5,
      stock: 10,
      isFeatured: true,
      description: "오늘의 요리는 오늘의 요리를 소개합니다. 맛있는 요리를 만들어보세요",
      createdAt: new Date(),
    },
    {
      id: 16,
      name: "오늘의 요리",
      slug: "/cooking-today-4",
      category: "Track Pants",
      images: ["/assets/images/p4-1.jpeg", "/assets/images/p4-2.jpeg"],
      price: "4000",
      brand: "the born korea",
      rating: "3.6",
      numReviews: 5,
      stock: 10,
      isFeatured: true,
      description: "오늘의 요리는 오늘의 요리를 소개합니다. 맛있는 요리를 만들어보세요",
      createdAt: new Date(),
    },
  ],
};

export const products = sampleData.products;

export default sampleData;
